### ISSUE TITLE
Windows Admin Center msft.sme.subnet-stretch has an error when populating the list of vms from Azure in step 3.2

### ISSUE THREAD

**Issue by CNewberry0** [microsoft/Windows-Admin-Center-Ideas-and-Feedback#131]
**Gateway Version**: 1.3.2111.01001
**Extension Version** 2.2.0

**To Reproduce**
1. Install the msft.sme.subnet-stretch extension
2. Navigate through the steps until you reach step 3
3. Select a resource group

**Expected behavior**
VM list should populate in "Select existing virtual machine" menu

**Screenshots & Additional context**
Error message from debug consol:
[{"source":"appErrorHandler","level":2,"message":"Cannot read properties of undefined (reading 'sku')","stack":"TypeError: Cannot read properties of undefined (reading 'sku')\n    at o.project (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:244:6688)\n    at o._next (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:1664:1980)\n    at o.next (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:192:3709)\n    at u.notifyNext (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:351:3151)\n    at s._next (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:182:9442)\n    at s.next (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:192:3709)\n    at u.notifyNext (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:351:3151)\n    at s._next (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:182:9442)\n    at s.next (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:192:3709)\n    at e._subscribe (https://localhost:6516/modules/msft.sme.subnet-stretch/main.bff33df471627a238879.js:1689:11598)","consoleGroupHeader":"Cannot read properties of undefined (reading 'sku')","sessionId":"15a4b03b-0823-44af-8ce3-a042fef4638e","timestamp":1645493362941,"sourceName":"msft.sme.subnet-stretch","sourceSubName":"main#1645493338389+2","sourceVersion":"0.1.0"}]
![Screenshot 2022-02-21 185415](https://user-images.githubusercontent.com/85502015/155044183-012ffd00-8305-4464-aaef-7e5700e75655.png)

**Comment by yanuoma** [comment]
Thanks for the original report, @CNewberry0, and apologies for the long delay in our triage cycle.

We've reviewed this against the current Windows Admin Center platform and believe the underlying behavior has been addressed. The product has evolved significantly since this report was filed.

If you can still reproduce this on a current WAC build, please reply here and we'll reopen with a fresh investigation — sharing your current Gateway build number and a short repro would help us a lot.

Thanks again for taking the time to write this up. 🙏

— The Windows Admin Center team
